version: "3.9"
services:
  sandbox:
    container_name: sandbox-2.0
    image: fidedocker/sandbox-2.0:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
